import { SCHEMA_STATEMENTS } from './statements';

export const DATABASE_STATE_KEY = 'database-state-v1'

export const TABLE_SCHEMA_STATEMENTS = SCHEMA_STATEMENTS.filter((statement) =>
  /^\s*CREATE TABLE IF NOT EXISTS/.test(statement),
)

export const INDEX_SCHEMA_STATEMENTS = SCHEMA_STATEMENTS.filter((statement) =>
  /^\s*CREATE (?:UNIQUE )?INDEX IF NOT EXISTS/.test(statement),
)

export const REQUIRED_COLUMNS: Readonly<Record<string, readonly string[]>> = {
  app_meta: ['key', 'value'],
  schema_migrations: ['version', 'applied_at'],
  users: ['id', 'username', 'password_hash', 'login', 'name', 'avatar_url', 'role', 'settings', 'created_at', 'last_seen_at'],
  folders: ['id', 'user_id', 'parent_id', 'name', 'icon', 'color', 'position', 'created_at', 'updated_at', 'deleted_at'],
  notes: ['id', 'user_id', 'folder_id', 'title', 'title_key', 'content', 'excerpt', 'rev', 'word_count', 'char_count', 'is_pinned', 'is_starred', 'is_archived', 'position', 'content_hash', 'created_at', 'updated_at', 'deleted_at'],
  tags: ['id', 'user_id', 'name', 'color', 'is_pinned', 'is_manual', 'created_at'],
  note_tags: ['note_id', 'tag_id'],
  links: ['source_note_id', 'target_key', 'target_title', 'target_note_id', 'user_id'],
  note_versions: ['id', 'note_id', 'user_id', 'title', 'content', 'size', 'created_at'],
  attachments: ['id', 'user_id', 'note_id', 'folder_id', 'filename', 'mime', 'size', 'sha256', 'width', 'height', 'storage', 'is_starred', 'is_pinned', 'tags', 'created_at'],
  attachment_folders: ['id', 'user_id', 'parent_id', 'name', 'icon', 'color', 'position', 'created_at', 'updated_at'],
  attachment_tags: ['id', 'user_id', 'name', 'color', 'is_pinned', 'created_at'],
  attachment_refs: ['user_id', 'attachment_id', 'count'],
  attachment_cleanup: ['object_key', 'user_id', 'created_at'],
  import_mappings: ['user_id', 'entity', 'source_id', 'target_id', 'updated_at'],
  backup_targets: ['id', 'user_id', 'type', 'name', 'enabled', 'config', 'secret', 'last_run_at', 'last_status', 'last_error', 'created_at', 'updated_at'],
  backup_runs: ['id', 'user_id', 'trigger', 'status', 'started_at', 'finished_at', 'note_count', 'file_count', 'bytes', 'detail'],
  shares: ['slug', 'note_id', 'user_id', 'folder_id', 'tags', 'password_hash', 'expires_at', 'views', 'is_enabled', 'last_viewed_at', 'created_at'],
  share_folders: ['id', 'user_id', 'parent_id', 'name', 'icon', 'color', 'position', 'created_at', 'updated_at'],
  share_tags: ['id', 'user_id', 'name', 'color', 'is_pinned', 'created_at'],
  share_visits: ['id', 'user_id', 'note_id', 'slug', 'visited_at', 'visitor_fp', 'country', 'region', 'city', 'referrer', 'referrer_host', 'device_type', 'os', 'browser', 'language', 'user_agent', 'is_bot', 'is_self_referrer', 'is_owner'],
  share_asset_sessions: ['id', 'slug', 'password_hash', 'expires_at', 'created_at'],
  changes: ['seq', 'user_id', 'entity', 'entity_id', 'op', 'at'],
  sessions: ['id', 'user_id', 'expires_at', 'created_at'],
  login_attempts: ['key', 'fails', 'last_fail_at', 'locked_until'],
  totp_credentials: ['user_id', 'secret_ciphertext', 'enabled_at', 'pending_token_hash', 'pending_session_id', 'pending_expires_at', 'recovery_generation', 'last_used_step', 'last_used_by', 'created_at', 'updated_at'],
  totp_recovery_codes: ['user_id', 'code_hash', 'generation', 'created_at', 'used_at', 'used_by'],
  totp_login_challenges: ['id', 'user_id', 'expires_at', 'claimed_by', 'created_at'],
  mcp_preferences: ['user_id', 'write_enabled', 'trash_enabled', 'updated_at'],
  mcp_operations: ['user_id', 'operation_id', 'tool', 'request_hash', 'response_json', 'created_at'],
  mcp_api_keys: ['id', 'user_id', 'name', 'key_hash', 'scopes', 'created_at', 'last_used_at', 'revoked_at'],
  ai_note_embeddings: ['user_id', 'note_id', 'model', 'vector', 'indexed_at'],
  ai_index_queue: ['user_id', 'note_id', 'kind', 'created_at'],
  fts_index_queue: ['user_id', 'note_id', 'kind', 'created_at'],
  community_templates: ['id', 'author_id', 'author_name', 'name', 'description', 'content', 'tags', 'category', 'created_at'],
  blog_posts: ['id', 'slug', 'note_id', 'user_id', 'title', 'excerpt', 'content', 'cover_url', 'category_id', 'folder_id', 'tags', 'is_published', 'allow_comments', 'is_pinned', 'views', 'published_at', 'created_at', 'updated_at'],
  blog_folders: ['id', 'user_id', 'parent_id', 'name', 'icon', 'color', 'position', 'created_at', 'updated_at'],
  blog_tags: ['id', 'user_id', 'name', 'color', 'is_pinned', 'created_at'],
  blog_categories: ['id', 'user_id', 'name', 'slug', 'description', 'color', 'icon', 'position', 'created_at', 'updated_at'],
  blog_comments: ['id', 'post_id', 'parent_id', 'author_name', 'author_email', 'author_url', 'author_avatar', 'content', 'status', 'ip', 'user_agent', 'created_at'],
  blog_visits: ['id', 'user_id', 'post_id', 'slug', 'visited_at', 'visitor_fp', 'country', 'region', 'city', 'referrer', 'referrer_host', 'device_type', 'os', 'browser', 'language', 'user_agent', 'is_bot', 'is_self_referrer', 'is_owner'],
} as const

export const REQUIRED_TABLES = [
  'app_meta',
  'schema_migrations',
  'users',
  'folders',
  'notes',
  'tags',
  'note_tags',
  'links',
  'note_versions',
  'attachments',
  'attachment_folders',
  'attachment_tags',
  'attachment_refs',
  'attachment_cleanup',
  'import_mappings',
  'backup_targets',
  'backup_runs',
  'shares',
  'share_folders',
  'share_tags',
  'share_visits',
  'share_asset_sessions',
  'changes',
  'sessions',
  'login_attempts',
  'totp_credentials',
  'totp_recovery_codes',
  'totp_login_challenges',
  'mcp_preferences',
  'mcp_operations',
  'mcp_api_keys',
  'ai_note_embeddings',
  'ai_index_queue',
  'fts_index_queue',
  'community_templates',
  'blog_posts',
  'blog_folders',
  'blog_tags',
  'blog_categories',
  'blog_comments',
  'blog_visits',
] as const

export const REQUIRED_INDEXES = [
  'idx_folders_user',
  'idx_folders_unique_sibling',
  'idx_notes_user_updated',
  'idx_notes_folder',
  'idx_notes_starred',
  'idx_notes_trash',
  'idx_notes_title_key',
  'idx_tags_unique',
  'idx_note_tags_tag',
  'idx_links_target',
  'idx_links_target_note',
  'idx_links_user_source',
  'idx_links_user_target',
  'idx_versions_note',
  'idx_attachments_user',
  'idx_attachments_user_sha',
  'idx_attachments_note',
  'idx_attachment_folders_user',
  'idx_attachment_folders_parent',
  'idx_attachment_tags_user',
  'idx_attachment_cleanup_created',
  'idx_attachment_cleanup_user',
  'idx_import_mappings_target',
  'idx_targets_user',
  'idx_runs_user',
  'idx_shares_note',
  'idx_shares_user',
  'idx_shares_folder',
  'idx_share_folders_user',
  'idx_share_folders_parent',
  'idx_share_tags_user',
  'idx_share_visits_user_time',
  'idx_share_visits_slug_time',
  'idx_share_visits_note_time',
  'idx_share_visits_filter_time',
  'idx_share_asset_sessions_slug',
  'idx_share_asset_sessions_expires',
  'idx_changes_user',
  'idx_sessions_user',
  'idx_sessions_expires',
  'idx_login_attempts_last_fail',
  'idx_totp_recovery_codes_user',
  'idx_totp_challenges_user',
  'idx_totp_challenges_expires',
  'idx_mcp_operations_created',
  'idx_mcp_api_keys_user',
  'idx_mcp_api_keys_revoked',
  'idx_ai_embeddings_indexed',
  'idx_ai_index_queue_due',
  'idx_fts_index_queue_due',
  'idx_community_templates_created',
  'idx_blog_posts_user',
  'idx_blog_posts_slug',
  'idx_blog_posts_note',
  'idx_blog_posts_category',
  'idx_blog_posts_folder',
  'idx_blog_folders_user',
  'idx_blog_folders_parent',
  'idx_blog_tags_user',
  'idx_blog_categories_slug',
  'idx_blog_categories_user',
  'idx_blog_comments_post',
  'idx_blog_comments_status',
  'idx_blog_visits_user_time',
  'idx_blog_visits_slug_time',
  'idx_blog_visits_post_time',
  'idx_blog_visits_filter_time',
] as const
