export { MusicStatusBar } from './music-status-bar'
export { MusicFloatingPlayer, MusicImmersiveOverlay } from './music-overlays-lazy'
export { MusicSessionSync } from './music-session-sync'
export { MusicHubModal } from './music-hub-lazy'
export { useMusic, useCurrentTrack, useVisibleTracks } from './music-store'
export { MUSIC_HOTKEYS } from './music-hotkeys'
export type { MusicPlaylistDetail, MusicScope, MusicSort, MusicTag, MusicTrack, MusicUploadTask } from './music-api-types'
