export { MusicStatusBar } from './music-status-bar'
export { MusicFloatingPlayer, MusicImmersiveOverlay } from './music-overlays-lazy'
export { MusicSessionSync } from './music-session-sync'
export { MusicHubModal } from './music-hub-lazy'
export { useMusic, useCurrentTrack, useVisibleTracks, IMMERSIVE_BACKGROUNDS, LYRIC_ALIGNS, LYRIC_SOURCES, LYRIC_TEXT_SIZES } from './music-store'
export type { MusicLyricSource } from './music-store'
export { listProviders } from './providers'
export { MusicEqPanel } from './music-transport-widgets'
export type { MusicProvider } from './providers'
export type { MusicImmersiveBackground, MusicLyricAlign, MusicLyricTextSize } from './music-store'
export { MUSIC_HOTKEYS } from './music-hotkeys'
export type { MusicPlaylistDetail, MusicScope, MusicSort, MusicTag, MusicTrack, MusicUploadTask } from './music-api-types'
